/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.howest.omartin.gui;

import be.howest.omartin.data.BiblioDA;
import be.howest.omartin.model.Genre;
import be.howest.omartin.model.Book;
import be.howest.omartin.util.BiblioException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author frederic
 */
public class BiblioFrame extends javax.swing.JFrame
{

    /**
     * Creates new form BiblioFrame
     */
    public BiblioFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGenres = new javax.swing.JList<>();
        btnGenreAdd = new javax.swing.JButton();
        btnGenreDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboGenres = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstBooks = new javax.swing.JList<>();
        btnBookAdd = new javax.swing.JButton();
        btnBookDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuFileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuHelpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Library Management System");

        jLabel2.setText("List of available genres:");

        lstGenres.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGenresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstGenres);

        btnGenreAdd.setText("Add");
        btnGenreAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreAddActionPerformed(evt);
            }
        });

        btnGenreDelete.setText("Delete");
        btnGenreDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenreDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenreAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenreAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenreDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Genres", jPanel1);

        jLabel3.setText("Genre:");

        cboGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenresActionPerformed(evt);
            }
        });

        jLabel4.setText("Books in selected genre:");

        lstBooks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBooksValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstBooks);

        btnBookAdd.setText("Add");
        btnBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAddActionPerformed(evt);
            }
        });

        btnBookDelete.setText("Delete");
        btnBookDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBookDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBookAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboGenres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBookAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Books", jPanel2);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        mnuFileExit.setText("Exit");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFileExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        mnuHelpAbout.setText("About...");
        mnuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpAboutActionPerformed(evt);
            }
        });
        jMenu2.add(mnuHelpAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showException(BiblioException ex)
    {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "An error occured", JOptionPane.ERROR_MESSAGE);
    }
    
    private void enableDisableControls()
    {
        btnBookDelete.setEnabled(lstBooks.getSelectedIndex() > -1);
        btnGenreDelete.setEnabled(lstGenres.getSelectedIndex() > -1);
    }
    
    private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuFileExitActionPerformed
    {//GEN-HEADEREND:event_mnuFileExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuFileExitActionPerformed

    private void mnuHelpAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuHelpAboutActionPerformed
    {//GEN-HEADEREND:event_mnuHelpAboutActionPerformed
        JOptionPane.showMessageDialog(rootPane, "(c) 2016 Frédéric Vlummens for Howest", 
                "About this application", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHelpAboutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        this.fillInGenreLists();
        this.enableDisableControls();
    }//GEN-LAST:event_formWindowOpened

    private void fillInGenreLists()
    {
        List<Genre> genres = BiblioDA.getInstance().getGenres();
        
        lstGenres.setListData(genres.toArray(new Genre[0]));
        
        cboGenres.removeAllItems();
        for (Genre genre : genres)
        {
            cboGenres.addItem(genre);
        }
    }
    
    private void btnGenreAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGenreAddActionPerformed
    {//GEN-HEADEREND:event_btnGenreAddActionPerformed
        String newGenre = JOptionPane.showInputDialog(this, "Please enter a name for the new genre", "Add genre", JOptionPane.QUESTION_MESSAGE);
        
        if (newGenre != null && !newGenre.trim().isEmpty())
        {
            Genre genre = new Genre(newGenre);
            
            try
            {
                BiblioDA.getInstance().addGenre(genre);
                this.fillInGenreLists();
            }
            catch (BiblioException ex)
            {
                this.showException(ex);
            }
        }
    }//GEN-LAST:event_btnGenreAddActionPerformed

    private void btnGenreDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGenreDeleteActionPerformed
    {//GEN-HEADEREND:event_btnGenreDeleteActionPerformed
        Genre genre = lstGenres.getSelectedValue();
        
        try
        {
            BiblioDA.getInstance().deleteGenre(genre);
            this.fillInGenreLists();
        }
        catch (BiblioException ex)
        {
            this.showException(ex);
        }
    }//GEN-LAST:event_btnGenreDeleteActionPerformed

    private void btnBookAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBookAddActionPerformed
    {//GEN-HEADEREND:event_btnBookAddActionPerformed
        BookDialog dlg = new BookDialog(this, true);
        dlg.setVisible(true);
        
        this.fillInBooks();
    }//GEN-LAST:event_btnBookAddActionPerformed

    private void btnBookDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBookDeleteActionPerformed
    {//GEN-HEADEREND:event_btnBookDeleteActionPerformed
        try
        {
            BiblioDA.getInstance().deleteBook(lstBooks.getSelectedValue());
            this.fillInBooks();
        }
        catch (BiblioException ex)
        {
            this.showException(ex);
        }
    }//GEN-LAST:event_btnBookDeleteActionPerformed

    private void cboGenresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cboGenresActionPerformed
    {//GEN-HEADEREND:event_cboGenresActionPerformed
        this.fillInBooks();
    }//GEN-LAST:event_cboGenresActionPerformed

    private void lstBooksValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_lstBooksValueChanged
    {//GEN-HEADEREND:event_lstBooksValueChanged
        this.enableDisableControls();
    }//GEN-LAST:event_lstBooksValueChanged

    private void lstGenresValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_lstGenresValueChanged
    {//GEN-HEADEREND:event_lstGenresValueChanged
        this.enableDisableControls();
    }//GEN-LAST:event_lstGenresValueChanged

    private void fillInBooks()
    {
        if (cboGenres.getSelectedIndex() > -1)
        {
            int genreId = ((Genre) cboGenres.getSelectedItem()).getId();

            lstBooks.setListData(BiblioDA.getInstance().getBooks(genreId).toArray(new Book[0]));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BiblioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BiblioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BiblioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BiblioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BiblioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAdd;
    private javax.swing.JButton btnBookDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenreAdd;
    private javax.swing.JButton btnGenreDelete;
    private javax.swing.JComboBox<Genre> cboGenres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<Book> lstBooks;
    private javax.swing.JList<Genre> lstGenres;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenuItem mnuHelpAbout;
    // End of variables declaration//GEN-END:variables
}
