package be.howest.ti.pokedex.ui;

import be.howest.ti.pokedex.model.Encounter;
import be.howest.ti.pokedex.model.PokedexApp;

public class PokedexFrame extends javax.swing.JFrame {

    private final PokedexApp app;

    public PokedexFrame(PokedexApp app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlTabs = new javax.swing.JTabbedPane();
        pnlSeenPokemon = new be.howest.ti.pokedex.ui.PokemonOverviewPanel();
        pnlSeenPokemon.setPokemon(app.getTrainer().getSeen());
        pnlOverviewEncounters = new be.howest.ti.pokedex.ui.OverviewEncounterPanel();
        pnlOverviewEncounters.setLocationSource(app);
        pnlAddEncounters = new be.howest.ti.pokedex.ui.ReportEncounterPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlWelcome.setText("Welcome");

        lblName.setText(getTrainerName());

        pnlTabs.addTab("Seen Pokemon", pnlSeenPokemon);
        pnlTabs.addTab("Overview Encounters", pnlOverviewEncounters);

        pnlAddEncounters.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pnlAddEncountersPropertyChange(evt);
            }
        });
        pnlTabs.addTab("Report Encounter", pnlAddEncounters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabs)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlWelcome)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddEncountersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnlAddEncountersPropertyChange
        if( evt.getPropertyName().equals("encounter")){
            reportEncounter((Encounter)evt.getNewValue());
            showDefault();
        }
    }//GEN-LAST:event_pnlAddEncountersPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblName;
    private be.howest.ti.pokedex.ui.ReportEncounterPanel pnlAddEncounters;
    private be.howest.ti.pokedex.ui.OverviewEncounterPanel pnlOverviewEncounters;
    private be.howest.ti.pokedex.ui.PokemonOverviewPanel pnlSeenPokemon;
    private javax.swing.JTabbedPane pnlTabs;
    private javax.swing.JLabel pnlWelcome;
    // End of variables declaration//GEN-END:variables

    void showDefault() {
        pnlSeenPokemon.setPokemon(app.getTrainer().getSeen());
        pnlTabs.setSelectedComponent(pnlSeenPokemon);
    }

    void reportEncounter(Encounter encounter) {
        app.getTrainer().encounter(encounter.getPokemon(), encounter.getLocation());
        showDefault();
    }
    
    private String getTrainerName(){
        return app.getTrainer().getName();
    }

}
